/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { NFTReward__factory } from "./NFTReward__factory";
export { Reward__factory } from "./Reward__factory";
